---
name: grandala
description: An obscure blue bird.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        - btop
        - eog
        - gnome-calculator
        - gnome-clocks
        - gnome-text-editor
        - gparted
        - qemu
        - libvirt
        - papers
        - screen
        - tailscale
        - telnet
        - virt-manager
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - gnome-software
        - gnome-system-monitor

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - ca.desrt.dconf-editor
          - com.brave.Browser
          - com.mattjakeman.ExtensionManager
          - com.ranfdev.DistroShelf
          - io.github.flattool.Ignition
          - io.github.kolunmi.Bazaar
          - io.missioncenter.MissionCenter
          - org.atheme.audacious
          - org.fedoraproject.MediaWriter
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.mozilla.firefox
          - org.remmina.Remmina
          - org.videolan.VLC
          - page.codeberg.libre_menu_editor.LibreMenuEditor
          - page.tesk.Refine

  - type: signing
